### ISSUE TITLE
Metric evaluation error: y_true and y_pred contain different number of classes

### ISSUE THREAD

**Issue by nicl-nno** [aimclub/FEDOT#1016] opened 2022-12-28 13:34 UTC
The problem "Metric evaluation error: y_true and y_pred contain different number of classes 45, 85" raises for click_prediction_small dataset

Looks like class stratification is failing.

**Comment by curiousHG** [comment] 2022-12-28 14:57
Can you expand on the issue? Or maybe narrow down to which file or code the problem is?

**Comment by nicl-nno** [comment] 2022-12-29 10:49
@curiousHG 

This problem occurs for classification tasks when the number of classes is very large and cross-validation fails to preserve the examples for all classes.

The connected problems are for <2 classes in sample and new classes in predict sample.

**Comment by gkirgizov** [comment] 2023-01-25 07:34
Duplicate of #954

**Comment by gkirgizov** [comment] 2023-01-25 07:34
Duplicate of https://github.com/aimclub/FEDOT/issues/954

**Closed by gkirgizov** 2023-01-25 07:34 UTC
Labels: bug
